lsi: false
safe: true
source: ./resources
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
git remote add origin https://github.com/Drifta01/github-pages.git